apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-deploy
spec:
 replicas: 4
 selector:
  matchLabels:
   app: product-app
 template: 
  metadata:
   labels:
    app: product-app
  spec:
   containers:
    - name: product-app
      image: victorhdcampos/product-app:0.1
      env:
      - name: DB_HOST
        value: "10.108.164.255"
      ports:
       - containerPort: 8083
      readinessProbe:
        httpGet:
          port: 8083
          path: /actuator/health
        initialDelaySeconds: 10
        failureThreshold: 3
        periodSeconds: 5
      livenessProbe:
        httpGet:
          port: 8083
          path: /actuator/health
   restartPolicy: Always	   