apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain	
  storageClassName: storage-grafana
  capacity:
    storage: 100Mi
  hostPath:
    path: /run/desktop/mnt/host/d/Development/Projects/workspace/Infnet/devops/grafana